### ISSUE TITLE
Hi i found your work intersting and would like to contribute. Can you please tell me how i can do that?

### ISSUE THREAD

**Issue by akshatgarg99** [ravenprotocol/raven-distribution-framework#22]

**Comment by syuan100** [comment]
@akshatgarg99 how would you like to contribute? The docs are currently being updated so it might not be clear where we need help, but there's work to be done in creating new ML algorithms based on our core libraries. If you have other interests there are other projects that could be done as well.

**Comment by akshatgarg99** [comment]
Thats great! I would love to make deep learning models using your framework or maybe build your framework so that is can support deep learning models

**Comment by akshatgarg99** [comment]
Is there anything on Reinforcement Learning?

**Comment by kailashahirwar** [comment]
@akshatgarg99 Not yet. But we are planning a library for reinforcement learning models.

**Comment by akshatgarg99** [comment]
That sounds exciting! Would love to contribute when that happens
